exclude = [
    "external",
    "lib",
    "stuff"
]

[lint]
ignore = [
  # E501 line too long (82 > 79 characters)
  "E501",
  # E402 module level import not at top of file
  "E402",  # module level import not at top of file
  # E731 do not assign a lambda expression, use a def
  "E731",  # do not assign a lambda expression
]
